### ISSUE TITLE
Charger les fichiers de façon asynchrone

### ISSUE THREAD

**Issue by younesaassila** [younesaassila/Vokabeln#6]
Les pages play.html et list.html pourraient bénéficier d'un écran de chargement afin d'avertir l'utilisateur que tout se passe comme prévu et qu'il est prié de patienter.

**Comment by Yougi3** [comment]
Le chargement devrait se faire de façon asynchrone.

**Comment by Yougi3** [comment]
Chargement asynchrone à implémenter. Cela devrait être assez simple en modifiant les méthodes de DataAccess en ajoutant un argument callback.
